# Generated by Django 5.1 on 2024-08-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro01", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author_book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="author_book",
            name="book",
        ),
        migrations.DeleteModel(
            name="board",
        ),
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
        migrations.AlterField(
            model_name="author",
            name="age",
            field=models.IntegerField(blank=True, help_text="年龄", null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.AutoField(help_text="作者id", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name="author",
            table="author",
        ),
        migrations.DeleteModel(
            name="Author_Book",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="UserType",
        ),
    ]
