# Generated by Django 5.1 on 2024-08-19 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pro01", "0002_remove_author_book_author_remove_author_book_book_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
    ]
