# Generated by Django 5.1 on 2024-08-19 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pro02", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
